name: Shell Commands

on: 
  #push:
  pull_request:
    types: [closed, opened, reopened]

jobs:
  run-shell-cmd:
    runs-on: ubuntu-latest
    
    steps:
    - name: List the root filesystem
      run: ls -l
    
    - name: run series of cmds
      run: |
        mkdir frankis
        node -v

    - name: ENV Displays
      run: |
         echo $GITHUB_SHA
         echo $GITHUB_REPOSITORY
         echo $GITHUB_TOKEN
         printenv
